using System.Collections.Generic;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Per-context client replication handler. Subscribes once to the
	// runtime's per-context RemoteEvent via EntitiesReplication.Subscribe
	// and dispatches each received op onto the local mirror entity.
	// EntitiesReplication.ShouldEmit() returns false on the client, so
	// the AddX/ReplaceX/RemoveX calls made here never echo back over the
	// wire.
	//
	// Entity identity is the server's creationIndex carried as `serverId`
	// in every op. The handler keeps a dictionary mapping serverId →
	// local entity; new entities are constructed lazily on the first Set
	// op for an unknown serverId. Remove ops on unknown serverIds are
	// dropped — within a single fire the ops array is in server-emit
	// order, so the client's Add/Replace decision is stable.
	//
	// Wire op shape (matches EntitiesReplication.luau):
	//   {opcode, componentIndex, entityId, ...fields}
	//   opcode 0 = Set, opcode 1 = Remove
	internal static class ClientReplicationTemplate
	{
		public static string Emit(ContextModel ctx, List<ComponentModel> replicated)
		{
			string entityType = $"{ctx.Name}Entity";
			string contextType = $"{ctx.Name}Context";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}ClientReplication");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate readonly {contextType} _context;");
			sb.AppendLine($"\tprivate readonly Dictionary<int, {entityType}> _byServerId = new();");
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}ClientReplication({contextType} context)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\t_context = context;");
			// Passes BuildDigest so the server's Ready handler can compare
			// our component layout against its own and kick on mismatch
			// — the only safe response when the two sides disagree on
			// componentIndex ↔ type mapping.
			sb.AppendLine($"\t\tEntitiesReplication.Subscribe(\"{ctx.Name}\", {ctx.Name}ComponentsLookup.BuildDigest, OnOps);");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// `out var x` doesn't lower today (DeclarationExpressionSyntax
			// gap), so use the ContainsKey + indexer pattern; both have
			// transpiler support per alpha.28.
			sb.AppendLine($"\tprivate {entityType} GetOrCreate(int serverId)");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tif (_byServerId.ContainsKey(serverId)) return _byServerId[serverId];");
			sb.AppendLine($"\t\t{entityType} created = _context.CreateEntity();");
			sb.AppendLine("\t\t_byServerId[serverId] = created;");
			sb.AppendLine("\t\treturn created;");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Receives a batch (server fires once per Heartbeat with every
			// op the tick produced). The cast pattern (object → object[])
			// mirrors how the transpiler lowers Lua tables to indexable
			// arrays in C#.
			sb.AppendLine("\tprivate void OnOps(object[] ops)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tfor (int i = 0; i < ops.Length; i++)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tobject[] op = (object[])ops[i];");
			sb.AppendLine("\t\t\tint opcode = (int)op[0];");
			sb.AppendLine("\t\t\tint compIndex = (int)op[1];");
			sb.AppendLine("\t\t\tint serverId = (int)op[2];");
			sb.AppendLine("\t\t\tif (opcode == 1) { ApplyRemove(compIndex, serverId); continue; }");
			sb.AppendLine("\t\t\tApplySet(compIndex, GetOrCreate(serverId), op);");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Set dispatch — choose Add vs Replace by HasX so the user
			// sees idempotent application of a re-sent op (the server can
			// resend on late join / re-sync without the client desyncing).
			sb.AppendLine($"\tprivate void ApplySet(int compIndex, {entityType} e, object[] op)");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in replicated)
			{
				sb.AppendLine($"\t\tif (compIndex == {ctx.Name}ComponentsLookup.{c.TypeName})");
				sb.AppendLine("\t\t{");
				if (c.IsFlag)
				{
					sb.AppendLine($"\t\t\te.Is{c.TypeName} = true;");
				}
				else
				{
					List<string> argList = new();
					for (int i = 0; i < c.Fields.Count; i++)
					{
						ComponentField f = c.Fields[i];
						// op[3] is first field, op[4] is second, etc.
						argList.Add($"({f.TypeFullName})op[{3 + i}]");
					}
					string args = string.Join(", ", argList);
					sb.AppendLine($"\t\t\tif (e.Has{c.TypeName}) e.Replace{c.TypeName}({args});");
					sb.AppendLine($"\t\t\telse e.Add{c.TypeName}({args});");
				}
				sb.AppendLine("\t\t\treturn;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();

			sb.AppendLine("\tprivate void ApplyRemove(int compIndex, int serverId)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tif (!_byServerId.ContainsKey(serverId)) return;");
			sb.AppendLine($"\t\t{entityType} e = _byServerId[serverId];");
			foreach (ComponentModel c in replicated)
			{
				sb.AppendLine($"\t\tif (compIndex == {ctx.Name}ComponentsLookup.{c.TypeName})");
				sb.AppendLine("\t\t{");
				if (c.IsFlag)
					sb.AppendLine($"\t\t\te.Is{c.TypeName} = false;");
				else
					sb.AppendLine($"\t\t\te.Remove{c.TypeName}();");
				sb.AppendLine("\t\t\treturn;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
