using System.Collections.Generic;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Per-context client replication handler. Subscribes once to the
	// runtime's per-context RemoteEvent via EntitiesReplication.Subscribe
	// and dispatches each received op onto the local mirror entity.
	// EntitiesReplication.ShouldEmit() returns false on the client, so
	// the AddX/ReplaceX/RemoveX calls made here never echo back over the
	// wire.
	//
	// Entity identity is the server's creationIndex carried as `serverId`
	// in every op. The handler keeps a dictionary mapping serverId →
	// local entity; new entities are constructed lazily on the first Set
	// op for an unknown serverId. Remove ops on unknown serverIds are
	// dropped — within a single fire the ops array is in server-emit
	// order, so the client's Add/Replace decision is stable.
	//
	// Wire op shape (matches EntitiesReplication.luau):
	//   Set:    {0, componentIndex, entityId, bitmask, ...changedFields}
	//   Remove: {1, componentIndex, entityId}
	// Bitmask tells us which positions in the changedFields tail hold
	// new values; positions whose bit is zero are unchanged and read
	// from the local component (frozen-clone safe — see Entity.luau's
	// GetReplicatedComponent).
	internal static class ClientReplicationTemplate
	{
		public static string Emit(ContextModel ctx, List<ComponentModel> replicated)
		{
			string entityType = $"{ctx.Name}Entity";
			string contextType = $"{ctx.Name}Context";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}ClientReplication");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate readonly {contextType} _context;");
			sb.AppendLine($"\tprivate readonly Dictionary<int, {entityType}> _byServerId = new();");
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}ClientReplication({contextType} context)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\t_context = context;");
			// Passes BuildDigest so the server's Ready handler can compare
			// our component layout against its own and kick on mismatch
			// — the only safe response when the two sides disagree on
			// componentIndex ↔ type mapping.
			// Pass the instance itself, not the OnOps method group — the
			// transpiler lowers a method-group argument to a bare function
			// (`self.OnOps`), so the runtime would call it without self.
			// EntitiesReplication.Subscribe colon-dispatches
			// `target:OnOps(ops)` instead.
			sb.AppendLine($"\t\tEntitiesReplication.Subscribe(\"{ctx.Name}\", {ctx.Name}ComponentsLookup.BuildDigest, this);");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// `out var x` doesn't lower today (DeclarationExpressionSyntax
			// gap), so use the ContainsKey + indexer pattern; both have
			// transpiler support per alpha.28.
			sb.AppendLine($"\tprivate {entityType} GetOrCreate(int serverId)");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tif (_byServerId.ContainsKey(serverId)) return _byServerId[serverId];");
			sb.AppendLine($"\t\t{entityType} created = _context.CreateEntity();");
			sb.AppendLine("\t\t_byServerId[serverId] = created;");
			sb.AppendLine("\t\treturn created;");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Receives a batch (server fires once per Heartbeat with every
			// op the tick produced). The cast pattern (object → object[])
			// mirrors how the transpiler lowers Lua tables to indexable
			// arrays in C#.
			sb.AppendLine("\tprivate void OnOps(object[] ops)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tfor (int i = 0; i < ops.Length; i++)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tobject[] op = (object[])ops[i];");
			sb.AppendLine("\t\t\tint opcode = (int)op[0];");
			sb.AppendLine("\t\t\tint compIndex = (int)op[1];");
			sb.AppendLine("\t\t\tint serverId = (int)op[2];");
			sb.AppendLine("\t\t\tif (opcode == 1) { ApplyRemove(compIndex, serverId); continue; }");
			sb.AppendLine("\t\t\tApplySet(compIndex, GetOrCreate(serverId), op);");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Set dispatch — choose Add vs Replace by HasX so the user
			// sees idempotent application of a re-sent op (the server can
			// resend on late join / re-sync without the client desyncing).
			// Per-component reconstruction: walk bits, pull new values
			// from op[4..] where the bit is set, fall back to the local
			// component's field where it's zero. The local read assumes
			// HasX — true whenever the bitmask isn't all-ones (server
			// guarantees: first-Set / Add always sends all-ones), but we
			// still guard with the default fallback for defense in depth.
			sb.AppendLine($"\tprivate void ApplySet(int compIndex, {entityType} e, object[] op)");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in replicated)
			{
				sb.AppendLine($"\t\tif (compIndex == {ctx.Name}ComponentsLookup.{c.TypeName})");
				sb.AppendLine("\t\t{");
				if (c.IsFlag)
				{
					// Flag: bitmask is 0, unused. Server only emits flag
					// Sets when the flag isn't already on (baseline check),
					// so this is effectively an Add — but Is{X}=true is
					// idempotent so a stale re-send is safe.
					sb.AppendLine($"\t\t\te.Is{c.TypeName} = true;");
				}
				else
				{
					sb.AppendLine("\t\t\tint bitmask = (int)op[3];");
					sb.AppendLine("\t\t\tint payloadIdx = 4;");

					bool unwrap = c.Fields.Count == 1 && c.Fields[0].Name == "Value";
					List<string> argList = new();

					for (int i = 0; i < c.Fields.Count; i++)
					{
						ComponentField f = c.Fields[i];
						int bit = 1 << i;
						string local = unwrap
							? $"e.{c.TypeName}"
							: $"e.{c.TypeName}.{f.Name}";
						// `e.{TypeName}` for unwrap returns the primitive
						// (frozen-clone path doesn't apply); for multi-
						// field it returns the frozen clone, then .Field
						// reads through the freeze.
						sb.AppendLine($"\t\t\t{f.TypeFullName} v{i} = (bitmask & {bit}) != 0");
						sb.AppendLine($"\t\t\t\t? ({f.TypeFullName})op[payloadIdx++]");
						sb.AppendLine($"\t\t\t\t: (e.Has{c.TypeName} ? {local} : default({f.TypeFullName}));");
						argList.Add($"v{i}");
					}

					string args = string.Join(", ", argList);
					sb.AppendLine($"\t\t\tif (e.Has{c.TypeName}) e.Replace{c.TypeName}({args});");
					sb.AppendLine($"\t\t\telse e.Add{c.TypeName}({args});");
				}
				sb.AppendLine("\t\t\treturn;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();

			sb.AppendLine("\tprivate void ApplyRemove(int compIndex, int serverId)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tif (!_byServerId.ContainsKey(serverId)) return;");
			sb.AppendLine($"\t\t{entityType} e = _byServerId[serverId];");
			foreach (ComponentModel c in replicated)
			{
				sb.AppendLine($"\t\tif (compIndex == {ctx.Name}ComponentsLookup.{c.TypeName})");
				sb.AppendLine("\t\t{");
				if (c.IsFlag)
					sb.AppendLine($"\t\t\te.Is{c.TypeName} = false;");
				else
					sb.AppendLine($"\t\t\te.Remove{c.TypeName}();");
				sb.AppendLine("\t\t\treturn;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
