using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Per-context client command sender. Registers a shipper fn at ctor
	// alongside the BuildDigest; the runtime calls the shipper at every
	// heartbeat for each entity in the pending set (built by IsCommand=true
	// setter tails). The shipper walks the entity's component indices and
	// emits one op per component currently on the entity — codegen knows
	// each component's field layout, so dispatch is a single switch on
	// componentIndex with one branch per component in the context.
	//
	// No whitelist by attribute — every component the user puts on a
	// command entity ships. Trust model: the user is responsible for
	// what they place on command entities. The server-side receiver
	// applies whatever arrives and tail-attaches OriginUserId from the
	// authenticated Player.
	internal static class ClientCommandSenderTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			string entityType = $"{ctx.Name}Entity";
			string contextType = $"{ctx.Name}Context";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}ClientCommandSender");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate readonly {contextType} _context;");
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}ClientCommandSender({contextType} context)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\t_context = context;");
			sb.AppendLine($"\t\tEntitiesReplication.ConfigureCommandSender(\"{ctx.Name}\", {ctx.Name}ComponentsLookup.BuildDigest, Ship);");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Per-entity shipper. Walks indices once, dispatches per
			// index. The clientLocalId is the entity's creationIndex —
			// stable across the ship operation and unique within the
			// client's session, so the server can collate multi-component
			// commands onto one server-side entity.
			sb.AppendLine($"\tprivate void Ship({entityType} e, List<object[]> ops)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tint clientLocalId = e.creationIndex;");
			sb.AppendLine("\t\tint[] indices = e.GetComponentIndices();");
			sb.AppendLine("\t\tfor (int i = 0; i < indices.Length; i++)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tint compIndex = indices[i];");

			// One branch per component in the context. Order doesn't
			// matter for correctness (the switch is exhaustive on the
			// indices the entity could carry); listing them in lookup
			// order keeps the file scannable.
			foreach (ComponentModel c in ctx.Components)
			{
				// OriginUserId is server-attached only; the client never
				// holds it on a command entity, so emitting a branch for
				// it would be dead code.
				if (c.IsSynthesizedOriginUserId) continue;

				string lookup = $"{ctx.Name}ComponentsLookup.{c.TypeName}";
				sb.AppendLine($"\t\t\tif (compIndex == {lookup})");
				sb.AppendLine("\t\t\t{");
				if (c.IsFlag)
				{
					sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ compIndex, clientLocalId }});");
				}
				else
				{
					bool unwrap = c.Fields.Count == 1 && c.Fields[0].Name == "Value";
					if (unwrap)
					{
						sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ compIndex, clientLocalId, e.{c.TypeName} }});");
					}
					else
					{
						sb.AppendLine($"\t\t\t\t{c.FullName} comp = e.{c.TypeName};");
						string fieldArgs = string.Join(", ", c.Fields.Select(f => $"comp.{f.Name}"));
						sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ compIndex, clientLocalId, {fieldArgs} }});");
					}
				}
				sb.AppendLine("\t\t\t\tcontinue;");
				sb.AppendLine("\t\t\t}");
			}

			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
