using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Emits the global Command flag class. One per project, injected into
	// every context's lookup unconditionally. Setting `entity.IsCommand =
	// true` is the client→server ship trigger: the synthesized flag's
	// setter tail (see EntityTemplate.Flag) marks the entity in the
	// pending set, and the next heartbeat drain ships its full component
	// set to the server. The flag also lives on the server-side spawned
	// entity so server systems can `AllOf<Command, ...>` on both sides
	// uniformly.
	internal static class CommandFlagClassTemplate
	{
		public static string Emit()
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine("public class Command : IComponent");
			sb.AppendLine("{");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
