using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// One file per (context, component) pair — the navigable unit of the
	// codegen. Holds the entity property/methods + the matcher static
	// getter + (for [Unique]) the context-level singleton accessors +
	// (for [EntityIndex] / [PrimaryEntityIndex]) the context-level dict +
	// lookup. The transpiler merges every partial back into one Luau class.
	internal static class ComponentTemplate
	{
		public static string Emit(ContextModel ctx, ComponentModel c)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();

			sb.AppendLine($"public sealed partial class {ctx.Name}Entity");
			sb.AppendLine("{");
			string lookup = $"{ctx.Name}ComponentsLookup.{c.TypeName}";
			if (c.IsFlag) EntityTemplate.EmitFlag(sb, ctx, c, lookup);
			else EntityTemplate.EmitValue(sb, ctx, c, lookup);
			sb.AppendLine("}");

			sb.AppendLine();

			sb.AppendLine($"public sealed partial class {ctx.Name}Matcher");
			sb.AppendLine("{");
			MatcherTemplate.EmitComponentGetter(sb, ctx, c);
			sb.AppendLine("}");

			if (c.IsUnique)
			{
				sb.AppendLine();
				UniqueContextPartialTemplate.Emit(sb, ctx, c);
			}

			if (c.HasIndexedField)
			{
				sb.AppendLine();
				IndexContextPartialTemplate.Emit(sb, ctx, c);
			}

			return sb.ToString();
		}
	}
}
