using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	internal static class ComponentsLookupTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			// `typeof(global::Code.Infrastructure.X)` carries the namespace
			// path through to the Lua emit verbatim — but the transpiler
			// only binds the bare type name as a local from CS.import. So
			// for typeof() we need `typeof(X)` (bare name), which needs
			// `using <namespace>;` at the top of the generated file. Pull
			// every component's containing namespace into the using set.
			HashSet<string> namespaces = new(StringComparer.Ordinal);
			foreach (ComponentModel c in ctx.Components)
			{
				string ns = c.NamespaceName;
				if (!string.IsNullOrEmpty(ns)) namespaces.Add(ns);
			}
			foreach (string ns in namespaces.OrderBy(s => s, StringComparer.Ordinal))
			{
				sb.AppendLine($"using {ns};");
			}
			sb.AppendLine();
			sb.AppendLine($"public static class {ctx.Name}ComponentsLookup");
			sb.AppendLine("{");
			for (int i = 0; i < ctx.Components.Count; i++)
			{
				sb.AppendLine($"\tpublic const int {ctx.Components[i].TypeName} = {i};");
			}
			sb.AppendLine($"\tpublic const int TotalComponents = {ctx.Components.Count};");
			sb.AppendLine();
			sb.AppendLine("\tpublic static readonly string[] componentNames =");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in ctx.Components) sb.AppendLine($"\t\t\"{c.TypeName}\",");
			sb.AppendLine("\t};");
			sb.AppendLine();
			sb.AppendLine("\tpublic static readonly System.Type[] componentTypes =");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in ctx.Components) sb.AppendLine($"\t\ttypeof({c.TypeName}),");
			sb.AppendLine("\t};");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
