using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	internal static class ContextTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed partial class {ctx.Name}Context : Context<{ctx.Name}Entity>");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic {ctx.Name}Context() : base({ctx.Name}ComponentsLookup.TotalComponents) {{ }}");
			sb.AppendLine($"\tpublic override {ctx.Name}Entity CreateEntityInstance() {{ return new {ctx.Name}Entity(); }}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
