using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	internal static class ContextsTemplate
	{
		public static string Emit(List<ContextModel> contexts, List<string> postConstructors)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine("public partial class Contexts : IContexts");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic static Contexts sharedInstance");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tget");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tif (_sharedInstance == null) _sharedInstance = new Contexts();");
			sb.AppendLine("\t\t\treturn _sharedInstance;");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t\tset { _sharedInstance = value; }");
			sb.AppendLine("\t}");
			sb.AppendLine("\tstatic Contexts _sharedInstance;");
			sb.AppendLine();
			foreach (ContextModel ctx in contexts)
			{
				sb.AppendLine($"\tpublic {ctx.Name}Context {LowerFirst(ctx.Name)} {{ get; set; }}");
			}
			sb.AppendLine();
			sb.AppendLine("\tpublic IContext[] allContexts");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tget {{ return new IContext[] {{ {string.Join(", ", contexts.Select(c => LowerFirst(c.Name)))} }}; }}");
			sb.AppendLine("\t}");
			sb.AppendLine();
			sb.AppendLine("\tpublic Contexts()");
			sb.AppendLine("\t{");
			foreach (ContextModel ctx in contexts)
			{
				sb.AppendLine($"\t\t{LowerFirst(ctx.Name)} = new {ctx.Name}Context();");
			}
			// [PostConstructor] tail-calls. Run after every per-context
			// field is wired so user code can register entity indices,
			// etc. without ordering surprises.
			if (postConstructors != null)
			{
				foreach (string name in postConstructors)
				{
					sb.AppendLine($"\t\t{name}();");
				}
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
			sb.AppendLine("\tpublic void Reset()");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tIContext[] all = allContexts;");
			sb.AppendLine("\t\tfor (int i = 0; i < all.Length; i++) all[i].Reset();");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		private static string LowerFirst(string s)
			=> string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
	}
}
