using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Base partial — the {Ctx}Entity shell with the inheritance line, plus
	// (when the context has any hooked components) a Destroy override that
	// pre-fires RemoveX / IsX = false so [Replicated] QueueRemove ops,
	// [Unique] _Clear hooks, and [EntityIndex] _Unregister hooks all run
	// before the base teardown wipes _components without notifying. Skips
	// the override entirely for hook-free contexts so the transpiler
	// doesn't waste a method on a no-op.
	//
	// EmitFlag and EmitValue (the per-component property emitters that
	// ComponentTemplate splices into each {Ctx}.{Component}.cs partial)
	// live in EntityTemplate.Flag.cs and EntityTemplate.Value.cs.
	internal static partial class EntityTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			List<ComponentModel> hooked = ctx.Components
				.Where(c => c.IsReplicated || c.IsUnique || c.HasIndexedField)
				.ToList();

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			if (hooked.Count == 0)
			{
				sb.AppendLine($"public sealed partial class {ctx.Name}Entity : Entity {{ }}");
				return sb.ToString();
			}

			sb.AppendLine($"public sealed partial class {ctx.Name}Entity : Entity");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic override void Destroy()");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in hooked)
			{
				if (c.IsFlag)
					sb.AppendLine($"\t\tif (Is{c.TypeName}) Is{c.TypeName} = false;");
				else
					sb.AppendLine($"\t\tif (Has{c.TypeName}) Remove{c.TypeName}();");
			}
			sb.AppendLine("\t\tbase.Destroy();");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
