using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	internal static class MatcherTemplate
	{
		// Base partial — only the shared AllOf/AnyOf factories live here.
		// Per-component static getters live in
		// Generated/Components/{Ctx}.{Component}.cs and merge in.
		public static string Emit(ContextModel ctx)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed partial class {ctx.Name}Matcher");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic static IAllOfMatcher<{ctx.Name}Entity> AllOf(params IMatcher<{ctx.Name}Entity>[] matchers)");
			sb.AppendLine($"\t\t=> Matcher.AllOf<{ctx.Name}Entity>(matchers);");
			sb.AppendLine($"\tpublic static IAnyOfMatcher<{ctx.Name}Entity> AnyOf(params IMatcher<{ctx.Name}Entity>[] matchers)");
			sb.AppendLine($"\t\t=> Matcher.AnyOf<{ctx.Name}Entity>(matchers);");
			sb.AppendLine("}");
			return sb.ToString();
		}

		// Per-component static-getter body — public so ComponentTemplate
		// can splice it into the per-component .cs.
		public static void EmitComponentGetter(StringBuilder sb, ContextModel ctx, ComponentModel c)
		{
			string field = $"_matcher{c.TypeName}";
			sb.AppendLine($"\tstatic IMatcher<{ctx.Name}Entity> {field};");
			sb.AppendLine($"\tpublic static IMatcher<{ctx.Name}Entity> {c.TypeName}");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tget");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tif ({field} == null)");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine($"\t\t\t\tMatcher<{ctx.Name}Entity> m = (Matcher<{ctx.Name}Entity>)Matcher.AllOfIndices<{ctx.Name}Entity>({ctx.Name}ComponentsLookup.{c.TypeName});");
			sb.AppendLine($"\t\t\t\tm.componentNames = {ctx.Name}ComponentsLookup.componentNames;");
			sb.AppendLine($"\t\t\t\t{field} = m;");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine($"\t\t\treturn {field};");
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
		}
	}
}
