using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Emits the global OriginUserId class file used by every context that
	// has at least one [Command] component. One Value:long field; lives in
	// the global namespace so the synthesized ComponentModel
	// (CreateOriginUserId) resolves it the same way across all contexts
	// without per-context type duplication. The runtime server-side
	// command receiver fills the Value from OnServerEvent's Player.UserId
	// before any system observes the new entity.
	internal static class OriginUserIdClassTemplate
	{
		public static string Emit()
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine("public class OriginUserId : IComponent");
			sb.AppendLine("{");
			sb.AppendLine("\tpublic long Value;");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
