using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Per-context server replication bootstrap. Registers a snapshotter
	// that the runtime calls when a new player's client fires the Ready
	// event. The snapshotter walks every live entity, checks each
	// replicated component's HasX, and appends a Set op carrying the
	// current field values. Order is GetEntities() order then codegen
	// order — stable within a snapshot but not relied on by the client.
	//
	// User code instantiates this once per context on the server, usually
	// next to the matching {Ctx}ClientReplication on the client. Both
	// guard internally on IsServer, so unconditional construction is
	// fine if you don't want to branch.
	internal static class ServerReplicationTemplate
	{
		public static string Emit(ContextModel ctx, List<ComponentModel> replicated)
		{
			string entityType = $"{ctx.Name}Entity";
			string contextType = $"{ctx.Name}Context";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}ServerReplication");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate readonly {contextType} _context;");
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}ServerReplication({contextType} context)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\t_context = context;");
			// RegisterDigest must precede RegisterSnapshotter: the
			// snapshot RemoteEvent's first OnServerEvent could fire as
			// soon as a player joins, and the Ready handler reads
			// _digests to validate. Ordering keeps that race closed.
			sb.AppendLine($"\t\tEntitiesReplication.RegisterDigest(\"{ctx.Name}\", {ctx.Name}ComponentsLookup.BuildDigest);");
			sb.AppendLine($"\t\tEntitiesReplication.RegisterSnapshotter(\"{ctx.Name}\", Snapshot);");
			sb.AppendLine("\t}");
			sb.AppendLine();

			// Snapshot — the late-join payload. Returns an ops array shaped
			// identically to a tick-time batch so the client dispatches it
			// through the same OnOps path.
			sb.AppendLine("\tprivate object[] Snapshot()");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\tList<object> ops = new();");
			sb.AppendLine($"\t\t{entityType}[] entities = _context.GetEntities();");
			sb.AppendLine("\t\tfor (int i = 0; i < entities.Length; i++)");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\t{entityType} e = entities[i];");
			foreach (ComponentModel c in replicated)
			{
				string lookup = $"{ctx.Name}ComponentsLookup.{c.TypeName}";
				if (c.IsFlag)
				{
					// Flag: no fields, bitmask = 0. Same wire shape as tick-
					// time Set for flags.
					sb.AppendLine($"\t\t\tif (e.Is{c.TypeName})");
					sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ 0, {lookup}, e.creationIndex, 0 }});");
				}
				else
				{
					// Snapshot ops always carry the all-ones bitmask — the
					// joining client has no local state for this entity yet
					// (we just created it via GetOrCreate), so every field
					// has to land in the apply path. The bitmask gives the
					// client's delta-decoder a uniform shape across snapshot
					// and tick batches.
					int allOnes = (1 << c.Fields.Count) - 1;
					bool unwrap = c.Fields.Count == 1 && c.Fields[0].Name == "Value";
					sb.AppendLine($"\t\t\tif (e.Has{c.TypeName})");
					sb.AppendLine("\t\t\t{");
					if (unwrap)
					{
						// Single Value field → unwrapped accessor reads
						// straight to the primitive.
						sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ 0, {lookup}, e.creationIndex, {allOnes}, e.{c.TypeName} }});");
					}
					else
					{
						// Multi-field → pull the component instance, then
						// unpack each field positionally.
						sb.AppendLine($"\t\t\t\t{c.FullName} comp = e.{c.TypeName};");
						string fieldArgs = string.Join(", ", c.Fields.Select(f => $"comp.{f.Name}"));
						sb.AppendLine($"\t\t\t\tops.Add(new object[] {{ 0, {lookup}, e.creationIndex, {allOnes}, {fieldArgs} }});");
					}
					sb.AppendLine("\t\t\t}");
				}
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t\treturn ops.ToArray();");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
