using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Per-context server-side receiver for client → server commands. The
	// runtime hands us batches as (player, ops[]); we collate ops by
	// clientLocalId so multiple components for the same logical command
	// land on one server-side entity, then apply each component by index
	// and attach OriginUserId from the Player. User systems pick up the
	// new entity via the normal group matcher path, typically via
	// CommandHandlerSystem<{Ctx}Entity>.
	//
	// Dispatch covers every component in the context (one branch per).
	// Without a per-component whitelist the client can ship any component
	// it likes — that's the dead-simple trust model. Server validates by
	// inspecting OriginUserId + the components present and acting (or
	// rejecting) per its own rules.
	//
	// Wire op shape (matches EntitiesReplication.luau):
	//   {componentIndex, clientLocalId, ...allFields}
	internal static class ServerCommandReceiverTemplate
	{
		public static string Emit(ContextModel ctx)
		{
			string entityType = $"{ctx.Name}Entity";
			string contextType = $"{ctx.Name}Context";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}ServerCommandReceiver");
			sb.AppendLine("{");
			sb.AppendLine($"\tprivate readonly {contextType} _context;");
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}ServerCommandReceiver({contextType} context)");
			sb.AppendLine("\t{");
			sb.AppendLine("\t\t_context = context;");
			sb.AppendLine($"\t\tEntitiesReplication.RegisterDigest(\"{ctx.Name}\", {ctx.Name}ComponentsLookup.BuildDigest);");
			sb.AppendLine($"\t\tEntitiesReplication.RegisterCommandReceiver(\"{ctx.Name}\", OnCommands);");
			sb.AppendLine("\t}");
			sb.AppendLine();

			sb.AppendLine($"\tprivate void OnCommands(object player, object[] ops)");
			sb.AppendLine("\t{");
			sb.AppendLine($"\t\tPlayer typedPlayer = (Player)player;");
			sb.AppendLine($"\t\tlong originUserId = typedPlayer.UserId;");
			sb.AppendLine();
			sb.AppendLine($"\t\tDictionary<int, {entityType}> spawnedByLocalId = new();");
			sb.AppendLine();
			sb.AppendLine("\t\tfor (int i = 0; i < ops.Length; i++)");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tobject[] op = (object[])ops[i];");
			sb.AppendLine("\t\t\tint compIndex = (int)op[0];");
			sb.AppendLine("\t\t\tint clientLocalId = (int)op[1];");
			sb.AppendLine();
			// Spawn-on-demand per clientLocalId. OriginUserId attaches
			// once at creation, before any client-shipped component,
			// so server systems observing the new entity always see
			// the trust marker.
			sb.AppendLine($"\t\t\t{entityType} e;");
			sb.AppendLine("\t\t\tif (spawnedByLocalId.ContainsKey(clientLocalId))");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\te = spawnedByLocalId[clientLocalId];");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine("\t\t\telse");
			sb.AppendLine("\t\t\t{");
			sb.AppendLine("\t\t\t\te = _context.CreateEntity();");
			sb.AppendLine("\t\t\t\te.AddOriginUserId(originUserId);");
			sb.AppendLine("\t\t\t\tspawnedByLocalId[clientLocalId] = e;");
			sb.AppendLine("\t\t\t}");
			sb.AppendLine();

			// Per-component dispatch. One branch per component in the
			// context — OriginUserId is excluded (server-attached, the
			// client never ships it).
			foreach (ComponentModel c in ctx.Components)
			{
				if (c.IsSynthesizedOriginUserId) continue;

				string lookup = $"{ctx.Name}ComponentsLookup.{c.TypeName}";
				sb.AppendLine($"\t\t\tif (compIndex == {lookup})");
				sb.AppendLine("\t\t\t{");
				if (c.IsFlag)
				{
					sb.AppendLine($"\t\t\t\te.Is{c.TypeName} = true;");
				}
				else
				{
					List<string> argList = new();
					for (int i = 0; i < c.Fields.Count; i++)
					{
						ComponentField f = c.Fields[i];
						argList.Add($"({f.TypeFullName})op[{2 + i}]");
					}
					string args = string.Join(", ", argList);
					sb.AppendLine($"\t\t\t\te.Add{c.TypeName}({args});");
				}
				sb.AppendLine("\t\t\t\tcontinue;");
				sb.AppendLine("\t\t\t}");
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
