using System.Collections.Generic;
using System.Text;

namespace RobloxCSharp.Extensions.Entities
{
	// Emits a per-context cleanup system that clears every Changed flag
	// at end of frame. User adds it to the tail of their feature
	// pipeline so reactive systems consuming `*Changed` see one-frame
	// signals. One system per context; one loop per [Watched] component.
	internal static class WatchedCleanupSystemTemplate
	{
		public static string Emit(ContextModel ctx, List<ComponentModel> watchedSources)
		{
			string entityType = $"{ctx.Name}Entity";

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/> roblox-csharp-entities");
			sb.AppendLine("using Entities;");
			sb.AppendLine();
			sb.AppendLine($"public sealed class {ctx.Name}WatchedCleanupSystem : ICleanupSystem");
			sb.AppendLine("{");
			foreach (ComponentModel c in watchedSources)
			{
				sb.AppendLine($"\tprivate readonly IGroup<{entityType}> _{LowerFirst(c.TypeName)}Changed;");
			}
			sb.AppendLine();
			sb.AppendLine($"\tpublic {ctx.Name}WatchedCleanupSystem({ctx.Name}Context context)");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in watchedSources)
			{
				sb.AppendLine($"\t\t_{LowerFirst(c.TypeName)}Changed = context.GetGroup({ctx.Name}Matcher");
				sb.AppendLine("\t\t\t.AllOf(");
				sb.AppendLine($"\t\t\t\t{ctx.Name}Matcher.{c.TypeName}Changed));");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
			sb.AppendLine("\tpublic void Cleanup()");
			sb.AppendLine("\t{");
			foreach (ComponentModel c in watchedSources)
			{
				sb.AppendLine($"\t\tforeach ({entityType} e in _{LowerFirst(c.TypeName)}Changed.GetEntities())");
				sb.AppendLine($"\t\t\te.Is{c.TypeName}Changed = false;");
			}
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		private static string LowerFirst(string s)
			=> string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
	}
}
